s3-sync:
  stage: deploy
  image: cohbot/aws-cli
  before_script:
    - BUILD_PATH=${BUILD_PATH:-"build"}
    - echo $BUILD_PATH
  script:
    - echo "syncing file to bucket ... $S3_DEPLOY_BUCKET"
    - aws s3 sync $BUILD_PATH s3://$S3_DEPLOY_BUCKET
  artifacts:
    paths:
    - build
    - www
    - dist
  only:
    - master



