version: "2"

services:
  app:
    image: ${IMAGE}
    depends_on:
      - mongo
      - postgres
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/tmp
      - PGUSER=admin
      - PGPASS=password
      - PGHOST=postgres
      - PGDATABASE=db
      - PGPORT=5432

  mongo:
    image: mongo:3.6
    volumes: 
      - ./.volumes/mongo-data:/data/db

  postgres:
    image: postgres:12.1-alpine
    volumes:
      - ./.volumes/postgres-data:/var/lib/postgresql/data 
      - ./.volumes/postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
